### ISSUE TITLE
Watch errors when moving/deleting files/folders

### ISSUE THREAD

**Issue by tipsy** [TelenorFrontend/docs-scaffold#65]
```
OS: Win10, 
NPM: 5.3.0
Node: 8.4.0
```
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at _errnoException (util.js:1041:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docs-scaffold@0.1.0 dev: `gulp watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docs-scaffold@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. 
         There is likely additional logging output above.
```

Haven't googled it yet, but I can investigate more later if necessary.

**Comment by oysteinsigholt** [comment]
Could this be the caused by [gulp-watch#291](https://github.com/floatdrop/gulp-watch/issues/291)?

I was not able to reproduce your exact error but got something similar when creating and deleting an empty folder in a folder watched by `gulp-watch`. If this is a major issue we could consider rewriting some of the globs to not watch sub directories.

**Comment by tipsy** [comment]
> If this is a major issue we could consider rewriting some of the globs to not watch sub directories.

You could also emit `end` on-error in gulp, or set ut plumber to do that for you.
